name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    paths:
      - 'content/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON files
        run: |
          find content -name "*.json" -exec node -e "
            try { 
              JSON.parse(require('fs').readFileSync('{}', 'utf8')); 
              console.log('✅ Valid: {}'); 
            } catch(e) { 
              console.error('❌ Invalid JSON: {}', e.message); 
              process.exit(1); 
            }
          " \;
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENGLISH_GO_CONTENT }}'
          channelId: live
          projectId: english-go-content
